{% set version = "1.0" %}

package:
  name: lprec
  version: {{ version }}

source:
  path: .

build:
  number: 0
  script: 
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('cxx') }}
    - python={{ python }} 
  host:
    - python={{ python }}
    - pip
    - setuptools
    - numpy
  run:
    - python={{ python }}
    - numpy
    - cupy      
    - cudatoolkit=10.0

about:
    home: https://github.com/math-vrn/lprec
    license: BSD 3-Clause
    license_family: BSD
    summary: 'Log-polar based method for tomographic reconstruction.'

